version: '3'
services:
  DiscordBotDb:
    image: mysql:8.0.32-debian
    platform: linux/amd64
    container_name: DiscordBotdb

    command: mysqld --innodb_use_native_aio=0

    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=master
      - TZ=Asia/Tokyo
      - MYSQL_TCP_PORT=9011


    ports:
      - '9011:3306'
      # - '33060:33060'

    expose:
      - 9011

    restart: always

    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/conf/my.conf:/etc/mysql/conf.d/my.conf:ro
      - ./db/logs:/var/log/mysql
      # data
      - ./db/data:/var/lib/mysql

  DiscordBotApp:
    image: node:latest
    container_name: DiscordBotApp

    environment:
      - MYSQL_HOST=DiscordBotDb
      - MYSQL_PORT=9011
      - TZ=Asia/Tokyo
      - SHIFTAPP_DEV=dev

    tty: true

    ports:
      - '9010:3000'

    restart: always

    volumes:
      - ../bot01:/bot01

    working_dir: /bot01

    depends_on:
      - DiscordBotDb

    command: make pm2
